const STATE={budget:parseFloat(localStorage.getItem('lx_budget'))||0,expenses:JSON.parse(localStorage.getItem('lx_expenses')||'[]'),savedPlaces:JSON.parse(localStorage.getItem('lx_saved')||'[]')};
function save(){localStorage.setItem('lx_budget',STATE.budget);localStorage.setItem('lx_expenses',JSON.stringify(STATE.expenses));localStorage.setItem('lx_saved',JSON.stringify(STATE.savedPlaces));}
document.addEventListener('DOMContentLoaded',()=>{setDefaultDate();initNav();initFilters();renderSuggestions('all');updateOverview();renderExpenses();renderCategorySummary();updateCountdown();if(STATE.budget>0){document.getElementById('budget-input').value=STATE.budget;showBudgetBar();updateChipBudget();}});
function updateCountdown(){const t=new Date('2026-05-30'),n=new Date();n.setHours(0,0,0,0);const d=Math.ceil((t-n)/86400000),e=document.getElementById('countdown-text');if(d>0)e.textContent=d+' days to Lisbon';else if(d===0)e.textContent='Trip starts today!';else e.textContent='Trip is underway ✈️';}
function initNav(){document.querySelectorAll('.nav-btn').forEach(b=>{b.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-section').forEach(s=>s.classList.remove('active'));b.classList.add('active');document.getElementById('tab-'+b.dataset.tab).classList.add('active');});});}
function initFilters(){document.querySelectorAll('.filter-pill').forEach(b=>{b.addEventListener('click',()=>{document.querySelectorAll('.filter-pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderSuggestions(b.dataset.filter);});});}
function renderSuggestions(f){const g=document.getElementById('suggestions-grid'),items=f==='all'?SUGGESTIONS:SUGGESTIONS.filter(s=>s.type===f);g.innerHTML=items.map(s=>suggestionCard(s)).join('');}
function suggestionCard(s){const sv=STATE.savedPlaces.includes(s.id),st='★'.repeat(s.rating)+'☆'.repeat(5-s.rating);return`<div class="suggest-card${s.mustDo?' must-do':''}"><span class="suggest-dot${s.mustDo?' gold':''}"></span><span class="suggest-emoji">${s.emoji}</span><div class="suggest-name">${s.name}</div><div class="suggest-area">📍 ${s.area}</div><div class="suggest-stars">${st}</div><div class="suggest-meta"><span class="meta-chip">${s.price}</span><span class="meta-chip">⏱ ${s.duration}</span></div><div class="suggest-cost">💶 ${s.cost}</div><p class="suggest-tip">${s.tip}</p><div class="suggest-tags">${s.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="save-row"><button class="save-btn${sv?' saved':''}" onclick="toggleSave(${s.id})">${sv?'❤️ Saved':'🤍 Save'}</button></div></div>`;}
function toggleSave(id){const i=STATE.savedPlaces.indexOf(id);if(i===-1){STATE.savedPlaces.push(id);showToast('Saved ❤️');}else{STATE.savedPlaces.splice(i,1);showToast('Removed');}save();updateOverview();renderSuggestions(document.querySelector('.filter-pill.active').dataset.filter);}
function setBudget(){const v=parseFloat(document.getElementById('budget-input').value);if(!v||v<=0){showToast('Enter a valid amount');return;}STATE.budget=v;save();showBudgetBar();updateOverview();updateChipBudget();showToast('Budget set: €'+v.toFixed(2));}
function updateChipBudget(){const e=document.getElementById('chip-budget');if(!STATE.budget){e.textContent='Set budget';return;}e.textContent='€'+Math.max(STATE.budget-totalSpent(),0).toFixed(0)+' remaining';}
function showBudgetBar(){document.getElementById('budget-bar-wrap').style.display='block';updateBudgetBar();}
function updateBudgetBar(){if(!STATE.budget)return;const s=totalSpent(),p=Math.min((s/STATE.budget)*100,100),f=document.getElementById('budget-bar-fill');f.style.width=p+'%';f.style.background=p>90?'var(--red)':p>70?'#f59e0b':'var(--green)';document.getElementById('budget-bar-spent').textContent='€'+s.toFixed(2)+' spent';document.getElementById('budget-bar-total').textContent='of €'+STATE.budget.toFixed(2);}
const CATEGORY_META={food:{label:'Food & Drink',emoji:'🍽️',color:'#f97316'},transport:{label:'Transport',emoji:'🚌',color:'#3b82f6'},accommodation:{label:'Accommodation',emoji:'🏨',color:'#8b5cf6'},activities:{label:'Activities',emoji:'🎟️',color:'#ec4899'},shopping:{label:'Shopping',emoji:'🛍️',color:'#14b8a6'},other:{label:'Other',emoji:'📦',color:'#6b7280'}};
function setDefaultDate(){document.getElementById('exp-date').value=new Date().toISOString().split('T')[0];}
function totalSpent(){return STATE.expenses.reduce((s,e)=>s+e.amount,0);}
function addExpense(){const d=document.getElementById('exp-desc').value.trim(),a=parseFloat(document.getElementById('exp-amount').value),c=document.getElementById('exp-category').value,dt=document.getElementById('exp-date').value;if(!d){showToast('Add a description');return;}if(!a||a<=0){showToast('Enter a valid amount');return;}if(!dt){showToast('Select a date');return;}STATE.expenses.unshift({id:Date.now(),desc:d,amount:a,category:c,date:dt});save();renderExpenses();renderCategorySummary();updateOverview();updateBudgetBar();updateChipBudget();document.getElementById('exp-desc').value='';document.getElementById('exp-amount').value='';setDefaultDate();showToast('€'+a.toFixed(2)+' added');}
function deleteExpense(id){STATE.expenses=STATE.expenses.filter(e=>e.id!==id);save();renderExpenses();renderCategorySummary();updateOverview();updateBudgetBar();updateChipBudget();showToast('Removed');}
function renderExpenses(){const l=document.getElementById('expense-list');document.getElementById('expense-total-badge').textContent='€'+totalSpent().toFixed(2);if(STATE.expenses.length===0){l.innerHTML='<p class="empty-state">Start tracking your Lisbon spending!</p>';return;}l.innerHTML=STATE.expenses.map(e=>{const m=CATEGORY_META[e.category],d=new Date(e.date+'T12:00:00'),ds=d.toLocaleDateString('en-GB',{day:'numeric',month:'short'});return`<div class="expense-item"><div class="expense-left"><div class="exp-cat-icon" style="background:${m.color}22">${m.emoji}</div><div><div class="exp-desc">${e.desc}</div><div class="exp-meta">${m.label} · ${ds}</div></div></div><div class="expense-right"><span class="exp-amount">€${e.amount.toFixed(2)}</span><button class="exp-del" onclick="deleteExpense(${e.id})">✕</button></div></div>`;}).join('');}
function renderCategorySummary(){const el=document.getElementById('category-summary');if(STATE.expenses.length===0){el.innerHTML='<p class="empty-state">No expenses yet.</p>';return;}const t={};STATE.expenses.forEach(e=>{t[e.category]=(t[e.category]||0)+e.amount;});const g=totalSpent();el.innerHTML=Object.entries(t).sort(([,a],[,b])=>b-a).map(([c,tot])=>{const m=CATEGORY_META[c],p=Math.round((tot/g)*100);return`<div class="cat-row"><div class="cat-row-top"><span class="cat-name">${m.emoji} ${m.label}</span><span class="cat-amt">€${tot.toFixed(2)} <small>(${p}%)</small></span></div><div class="cat-bar"><div class="cat-bar-fill" style="width:${p}%;background:${m.color}"></div></div></div>`;}).join('');}
function updateOverview(){const s=totalSpent(),r=STATE.budget?Math.max(STATE.budget-s,0):0;document.getElementById('ov-spent').textContent='€'+s.toFixed(0);document.getElementById('ov-remaining').textContent=STATE.budget?'€'+r.toFixed(0):'—';document.getElementById('ov-places').textContent=STATE.savedPlaces.length;document.getElementById('ov-transactions').textContent=STATE.expenses.length;}
function showAdvice(k){const d=ADVICE[k];if(!d)return;document.getElementById('advice-icon').textContent=d.icon;document.getElementById('advice-title').textContent=d.title;document.getElementById('advice-body').innerHTML=d.body;const c=document.getElementById('advice-card');c.style.display='block';c.scrollIntoView({behavior:'smooth',block:'nearest'});if(d.showPacking){renderPackingList();document.getElementById('packing-section').style.display='block';}}
function renderPackingList(){const k='lx_packed',p=JSON.parse(localStorage.getItem(k)||'[]'),el=document.getElementById('packing-list');el.innerHTML=PACKING_ITEMS.map(cat=>`<div class="packing-category"><div class="packing-cat-title">${cat.category}</div>${cat.items.map(item=>{const id=btoa(unescape(encodeURIComponent(item))).replace(/=/g,''),ch=p.includes(id);return`<label class="packing-item${ch?' packed':''}" ><input type="checkbox" ${ch?'checked':''} onchange="togglePacked('${id}',this)" /><span>${item}</span></label>`;}).join('')}</div>`).join('');}
function togglePacked(id,cb){const k='lx_packed',p=JSON.parse(localStorage.getItem(k)||'[]');if(cb.checked)p.push(id);else{const i=p.indexOf(id);if(i>-1)p.splice(i,1);}localStorage.setItem(k,JSON.stringify(p));cb.closest('label').classList.toggle('packed',cb.checked);}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400);}